name: what_4_lunch
description: A project to help deciding what to eat for lunch.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  vibration: ^1.0.1

  android_intent: ^0.2.1

  url_launcher: ^4.0.3

  http: ^0.12.0+1

  location: ^1.4.1

  rxdart: ^0.20.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  